### ISSUE TITLE
Problem generating with Oxygen 24 on Windows

### ISSUE THREAD

**Issue by gabysegalla** [jason-fox/fox.jason.passthrough.pandoc#9]
We don't ever use the terminal to generate DITA docs - only Oxygen. 

My Pandoc executable is located here on my machine: C:\Users\gscott\AppData\Local\Pandoc\
I use a plugin directory outside of Oxygen. dita.dir=C:\DITA-OT

I uncommented and set configuration.properties:  pandoc.dir=C:\Users\gscott\AppData\Local\

Am I entering the path incorrectly? Here's the log: [oxygenlog.txt](https://github.com/jason-fox/fox.jason.passthrough.pandoc/files/7951630/oxygenlog.txt)

**Comment by jason-fox** [comment]
The underlying problem is shown in your log here - the pandoc check has failed:

```
pandoc.check:
   [pandoc] Result: 1
[PAND001W][WARN] Pandoc has not been installed
```

The path may need to use UNIX rather than Windows formatting, I'm not sure. Try it with forward slashes maybe? Rerun the test adding the `-d` flag to get a more verbose output, and attach the debug log.

**Comment by gabysegalla** [comment]
I tried using forward slashes. It didn't seem to change anything. Here's the verbose output.
[oxygenlog.txt](https://github.com/jason-fox/fox.jason.passthrough.pandoc/files/7970773/oxygenlog.txt)

**Comment by jason-fox** [comment]
That is not quite verbose enough, try:

```
./dita -i ../plugins/dita-bootstrap/sample/document.ditamap -f html5 -d
```

A successful run will give:

```text
pandoc.check:
 [property] Loading /Users/jasonfox/Workspace/dita/dita-ot-3.7/plugins/fox.jason.passthrough.pandoc/cfg/configuration.properties
   [pandoc] Current OS is Mac OS X
   [pandoc] Output redirected to property: pandoc.out
   [pandoc] Executing 'pandoc' with arguments:
   [pandoc] '-v'
   [pandoc] 
   [pandoc] The ' characters around the executable and arguments are
   [pandoc] not part of the command.
   [pandoc] pandoc 2.11.2
   [pandoc] Compiled with pandoc-types 1.22, texmath 0.12.0.3, skylighting 0.10.0.3,
   [pandoc] citeproc 0.2, ipynb 0.1.0.1
   [pandoc] User data directory: /Users/jasonfox/.local/share/pandoc or /Users/jasonfox/.pandoc
   [pandoc] Copyright (C) 2006-2020 John MacFarlane. Web:  https://pandoc.org
   [pandoc] This is free software; see the source for copying conditions. There is no
   [pandoc] warranty, not even for merchantability or fitness for a particular purpose.
```

**Comment by jason-fox** [comment]
You have two separate issues here - neither *Pandoc*  nor *SwaggerGen* are working for you:

```text
swagger.process:
 [gen-list] [swagger-gen] Java Result: 1
 [gen-list] [swagger-gen] Exception in thread "main" com.google.common.collect.Ordering$IncomparableValueException: Cannot compare value: null
 [gen-list] [swagger-gen] 	at com.google.common.collect.ExplicitOrdering.rank(ExplicitOrdering.java:45)
 [gen-list] [swagger-gen] 	at com.google.common.collect.ExplicitOrdering.compare(ExplicitOrdering.java:39)
 [gen-list] [swagger-gen] 	at com.google.common.collect.ByFunctionOrdering.compare(ByFunctionOrdering.java:43)
 [gen-list] [swagger-gen] 	at com.google.common.collect.CompoundOrdering.compare(CompoundOrdering.java:40)
 [gen-list] [swagger-gen] 	at io.github.swagger2markup.internal.component.ParameterTableComponent.lambda$apply$0(ParameterTableComponent.java:72)
 [gen-list] [swagger-gen] 	at java.base/java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
```

This one is outside of my control - the [swagger2markup](https://github.com/Swagger2Markup/swagger2markup) library does not recognize your swagger as valid.

**Comment by jason-fox** [comment]
Goto `https://editor.swagger.io/` and check to see if your swagger file is valid. I've found the YAML format is usually more correct than the JSON format.  It would be easier to fix the Pandoc issue if you tested using the existing simple [markdown test](https://github.com/jason-fox/fox.jason.passthrough.pandoc/tree/master/test/input-markdown) first.

**Comment by jason-fox** [comment]
`Cannot compare value: null` is due to a missing parameter within the Swagger file somewhere.
